### ISSUE TITLE
Mercurial Exchange keeps logging a 6003 error

### ISSUE THREAD

**Issue by jbrit** [jup-ag/jupiter-cpi#1]
I'm currently trying to use this crate here:

https://github.com/jbrit/anchor-swap/blob/main/programs/swap/src/lib.rs

I'm pretty sure I set it up correctly, for some reason I keep getting the 6003 error, MissingMercurialExchangeTokenAccount.

Would like to know what's wrong and possibly ask if some errors that aren't too clear can be documented

**Comment by chinepun** [comment]
Check this [out](https://github.com/jup-ag/instruction-parser/blob/main/src/idl/jupiter.json#L2038:)

**Comment by jbrit** [comment]
Thanks @chinepun It I was supposed to pass remaining accounts not specified to the cpi context
